services:
  mydj:
    image: mydj:latest
    ports:
      - "9000:9000"

  mydjq:
    image: "mysql:latest"
    restart: always
    ports:
      - "9010:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "mydjqv:/var/lib/mysql"

  mydjqadm:
    image: "phpmyadmin:latest"
    restart: always
    ports:
      - "9020:80"
    depends_on:
      - mydjq
    links:
      - "mydjq:db"

networks:
  mydjqnw:

volumes:
  mydjqv:
    driver: local
