services:
  mydj:
    image: mydj:latest
    command:
      - "0.0.0.0:9001"  # Push the command line arguments into ENTRYPOINT, bypass CMD
    ports:
      - "9000:9001"  # container CMD port will be updated by 'command'
    environment:
      HOST: 'mydjq'  # mysql Host for django -> From docker and From local are different
      PORT: '3306'  # mysql port for django -> From docker and From local are different
    depends_on:
      - mydjq

  mydjq:
    image: "mysql:latest"
    restart: always
    ports:
      - "9010:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "mydjqv:/var/lib/mysql"

  mydjqadm:
    image: "phpmyadmin:latest"
    restart: always
    ports:
      - "9020:80"
    depends_on:
      - mydjq
    links:
      - "mydjq:db"

networks:
  mydjqnw:

volumes:
  mydjqv:
    driver: local
